### ISSUE TITLE
Calling freeBuffer correctly to avoid Memory Out of Bounds

### ISSUE THREAD

**Issue by JonMidhir** [hellwolf/haskell-examples#1]
Ref: https://github.com/hellwolf/haskell-examples/blob/master/2023-02-24-wasm-comm/client.js

@hellwolf This example has some really useful utilities for working with strings in Haskell WASM reactors. Thank you for publishing it!

I was wondering about these two functions:

```js
function withCStrings(strs, op) {
    const cstrs = strs.map(str => {
        const s = new TextEncoder().encode(str);
        const l = s.length + 1;
        const p = inst.exports.callocBuffer(l);
        const b = new bufferAt(p, l);
        b.set(s);
        return p;
    });
    const r = op(cstrs);
    strs.forEach(inst.exports.freeBuffer);
    return r;
}
```

```js
function fromCString(cstr) {
    const s = new TextDecoder("utf8").decode(cstringBufferAt(cstr));
    inst.exports.freeBuffer(cstr);
    return s;
}
```

In the first function `freeBuffer` is called on `strs` which is presumed to be an array of `utf-8` encoded strings.

In the second function `freeBuffer` is called on `cstr`, the CString representation of a string.

Is there a reason for the inconsistency? I would expect that `freeBuffer` use is correct in `fromCString` but this actually causes intermittent Memory Out of Bounds errors for me. Changing it to `inst.exports.freeBuffer(s);` so that it's operating on the `utf-8` encoded string solves these but I have no idea why.

**Comment by hellwolf** [comment]
Hi @JonMidhir !

Thanks for reporting this. I am glad that it was useful for you, and I am happy you actually found it! This repo was mostly of my own scribbles, rarely publicized :)

> Is there a reason for the inconsistency?

I can't recall, I need to look again.

I suspect `inst.exports.freeBuffer(s);` is not actually helping since it seems to be creating a memory leak that's less noticeable than crashing otherwise.

**Comment by JonMidhir** [comment]
I did some follow up here, you can read the findings in https://gitlab.com/gitlab-org/gitlab-query-language/gitlab-query-language/-/merge_requests/41.

I'm not sure why `strs.forEach(inst.exports.freeBuffer);` ever worked for me (but it did in 99% of cases). `strs` is an array of UTF-8 encoded strings. What we want to pass to `freeBuffer` is a pointer to a memory location. This is contained in `cstrs` so the fix is simply `cstrs.forEach(inst.exports.freeBuffer);` as I expected.

I was still getting out of bounds errors though and that's because I was using `fromCString` to try to free up memory used by [`useAsCStringLen`](https://hackage.haskell.org/package/bytestring-0.12.1.0/docs/Data-ByteString.html#v:useAsCStringLen) , which does its own memory management.

Thanks for the response @hellwolf ! Got there in the end.

**Comment by hellwolf** [comment]
Thank you for digging into it!

I think your changes make sense, I will fix my example!

**Comment by hellwolf** [comment]
https://github.com/hellwolf/haskell-examples/commit/d33b4e2613b3bf720c013401b42e8de573cdf185

Cheers!
